### ISSUE TITLE
Hyperlinks not found on mobile WhatsApp client

### ISSUE THREAD

**Issue by lc1294** [yapyeeqiang/whatsapp-sender#3]
The messages sent via the message text does not include the hyperlink when viewed on mobile (Whatsapp Web, multi-device beta). The text in the txt file does indicate that there is a hyperlink. The issue is unique to mobile, the desktop clients (of Whatsapp Web) display the hyperlink without issue.

But on WhatsApp Web stable (without multi-device feature), the messages have not issue.

Probably unique to the WhatsApp Beta.

Attached is a screenshot of the sent messages, along with the associated message.txt

[message.txt](https://github.com/yapyeeqiang/whatsapp-sender/files/7773821/message.txt)

![Screenshot_20211224-175703_WhatsApp](https://user-images.githubusercontent.com/45134299/147342978-4add9a5f-61b2-473e-800e-b3b956313276.png)

**Comment by yapyeeqiang** [comment]
## Solved
The issue is due to `WhatsApp Multi Device Beta`.
