### ISSUE TITLE
Invalid phone number requires manual input to skip (WA states invalid URL)

### ISSUE THREAD

**Issue by lc1294** [yapyeeqiang/whatsapp-sender#4]
Hey @yapyeeqiang , can an auto skip function be added into the script?

Because in the list of contact that we have for mass outreach, there are invalid numbers.

In the current implementation of the script, it requires manual action to skip invalid numbers on WhatsApp Web and the script itself.

Attached is a video recording of the behavior stated:
[https://www.loom.com/embed/8844f6dc896848b6b6dd4bb577a6dfa5](url)

Here's a small selection of numbers to highlight the behavior 
[message.txt](https://github.com/yapyeeqiang/whatsapp-sender/files/7795266/message.txt)

**Comment by yapyeeqiang** [comment]
Hey @lc1294, I would like to clarify is the phone number limited to Malaysia zone only? If yes, I can do a simple check on the format on the phone number based on Malaysia. Else will have to use some external API.

**Comment by lc1294** [comment]
@yapyeeqiang The phone number are a mix of Malaysia, Singapore, and Philippines. There are others countries too, but have not checked specifically which country. I tried my best to keep the list consistent, but as there are 2.3k individual numbers, a substantial amounts will slip through the cracks.

Attached is the full list, the numbers are not organized in any particular order.
[contacts.txt](https://github.com/yapyeeqiang/whatsapp-sender/files/7795747/contacts.txt)

**Comment by yapyeeqiang** [comment]
@lc1294 Do you have the list that comes with their country instead of just a list of phone numbers?

**Comment by lc1294** [comment]
@yapyeeqiang no, but the number listed have their country code in first 2 number of their phone number. 65 for Singapore, 63 for Philippines,  60 for Malaysia.

**Comment by yapyeeqiang** [comment]
@lc1294 Actually phone number is invalid might also means that the user input is phone number incorrectly. I also do a double check on some invalid numbers, they indeed either don't have WhatsApp, or they input their phone number format wrongly

**Comment by yapyeeqiang** [comment]
@lc1294 Do you have any example of phone number that you are 100% sure it is valid and they are on WhatsApp?

**Comment by lc1294** [comment]
So far the numbers that are valid are Malaysian numbers, the list does not guarantee they have WhatsApp, as it was submitted via the old website forms and what not. The initial assumption is that most of they may have WhatsApp. Just looking for a way to automatically skip those that do not have or have submitted invalid numbers, without requiring manual input to continue the process.

**Comment by yapyeeqiang** [comment]
Hey @lc1294, I pushed the latest fix, please try again and let me know how's it going.

Your terminal should show this if it is an invalid phone number:
```sh
1/3 => Sending message to 60198248014.
Message sent to: 60198248014


2/3 => Sending message to 601231231.
Something went wrong...
Failed to send message to this contact: 601231231.
```

You will also have all the invalid contacts in the text file in your folder:
![image](https://user-images.githubusercontent.com/63979210/147817752-932fa4ac-6093-4b79-a1cd-70eca75f59d9.png)

**Comment by yapyeeqiang** [comment]
## Steps

To update your current code downloaded:
```sh
git pull origin master
```

Let me know if you never use `git` before and don't have them installed in your machine. We will go through it in separately.
